# Exemplos Básicos - NumPy

In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2],[3, 4]])
a

array([[1, 2],
       [3, 4]])

In [3]:
a[1][1]

4

In [4]:
b=a.transpose()

In [5]:
b

array([[1, 3],
       [2, 4]])

In [6]:
c=a+b
c

array([[2, 5],
       [5, 8]])

In [7]:
c-b

array([[1, 2],
       [3, 4]])

In [8]:
a*b

array([[ 1,  6],
       [ 6, 16]])

In [9]:
a.sum()

10

In [10]:
a.trace()

5

In [11]:
a.item(1)

2

In [12]:
a.max()

4